# Makefile auto generated by mk 2.0
#
# Targets:
# - main

# Compiler Options:
CXXC = g++
CC = gcc
CXXFLAGS = -Wall -Wextra -pedantic
CFLAGS = -Wall -Wextra -pedantic
LDFLAGS = -lm

# Target Executables:
MAIN_EXE = main

# Object Files:
MAIN_OBJS = main.o \
 basic_math.o

# Phony Targets:
.PHONY: all clean

# All Targets:
all: $(MAIN_EXE)

# Targets:
$(MAIN_EXE): $(MAIN_OBJS)
	$(CC) $(CFLAGS) $(MAIN_OBJS) -o $(MAIN_EXE) $(LDFLAGS)

# Clean:
clean:
	rm -f $(MAIN_EXE) $(MAIN_OBJS)

# Rules:
.cpp.o:
	$(CXXC) $(CXXFLAGS) -c $< -o $@
.c.o:
	$(CC) $(CFLAGS) -c $< -o $@

# Dependencies:
main.o: main.c ctest.h basic_math.h
basic_math.o: basic_math.c basic_math.h

